apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: prmi2x94u-java-quarkus 
  janus-idp.io/tekton: prmi2x94u-java-quarkus
  backstage.io/kubernetes-id: prmi2x94u-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: prmi2x94u-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml