apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: prmi2x94u-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-78c1a5f0d6.yand.p3.openshiftapps.com/rhtap/rhtap-qe-java-quarkus:2e525109b476c2f9892300de3c95defc40f52884@sha256:69bf81a77a5b36db1d200552bbf7a8cf5abfef0184609e2ddf94ac479f571d6f
        name: container-image  
